### ISSUE TITLE
Unspecifed option specified on `experimental.strict_type_args`

### ISSUE THREAD

**Issue by fadils** [AtomLinter/linter-flow#122]
```
Error: .flowconfig:39 Unsupported option specified! (experimental.strict_type_args)
    at ChildProcess.<anonymous> (/Users/fadils/.atom/packages/linter-flow/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by nmn** [comment]
This is a flow error, not a linter-flow error, and pretty self-descriptive.
