### ISSUE TITLE
Error: Unhandled Exception: End_Of_File 

### ISSUE THREAD

**Issue by tomitrescak** [AtomLinter/linter-flow#131]
Hi, I keep receiveing following error quite often:

```
Error: Unhandled exception: End_of_file
    at ChildProcess.<anonymous> (/Users/tomi/.atom/packages/linter-flow/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:41:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

I have mixed javascript and typescript files. Any idea what could be the problem?

**Comment by Arcanemagus** [comment]
Do you consistently see this? Are you able to share the files you see this on if so?

**Comment by nmn** [comment]
Funnily, I started getting these errors recently too. But from a `linter-eslint`.

**Comment by bgeihsgt** [comment]
@Arcanemagus here's a file I'm consistently seeing this on:

```
// @flow
import chai from 'chai';
const expect = chai.expect;

import {
  authenticate,
  createAgent
} from '../../../fixtures';

describe('Foo, function() {

  let agent, user;

  beforeEach(async function() {
    agent = await createAgent();
    user = await authenticate(agent);
  });

});
```

Callstack:

```
Error: Unhandled exception: End_of_file
    at ChildProcess.<anonymous> (/Users/briangeihsler/.atom/packages/linter-flow/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:41:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by bgeihsgt** [comment]
It pops up regularly any time I'm typing. I need to disable the package when working in certain files :/

**Comment by nmn** [comment]
I think this is an issue with the `linter` package itself. Ive seen this error on and off in both linter-flow and linter-eslint.

**Comment by bgeihsgt** [comment]
@nmn If that was the case, then why would the problem go away when I disable `linter-flow` but keep `linter-eslint` on?

**Comment by nmn** [comment]
@bgeihsgt I don't know. I'm just reporting what I've experienced personally.

Lately, I can't reproduce the error at all. But if you could open up the console when you see this error and send us the stack trace that would be very helpful.

**Comment by bgeihsgt** [comment]
@nmn I opened up the console and repro'd the red box but saw nothing on the console. Is the strack trace from the red box not sufficient?

```
Error: Unhandled exception: End_of_file
    at ChildProcess.<anonymous> (/Users/briangeihsler/.atom/packages/linter-flow/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:41:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by Arcanemagus** [comment]
Unfortunately the only part of that stack trace that means anything is `Unhandled exception: End_of_file`, which is coming from the `stderr` output of the command (`flow`). Why `flow` is returning that is the question...

@nmn I've yet to see a report on `linter-eslint` that shows that, are you sure it's not just `flow` running on the same files and hitting the same thing?

**Comment by Arcanemagus** [comment]
Possibly related to https://github.com/facebook/flow/issues/1693, it looks like there are a few different issues over there related to this message.

**Comment by jbmorgado** [comment]
I'm still receiving this error on atom while using linter-flow. On VSCode with *Flow Language Support* module, it works fine.

**Comment by huzidaha** [comment]
It's maybe you don't have `eslint` package installed in your project, use:

```
npm install eslint --save-dev
```
