### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by burabure** [AtomLinter/linter-flow#15]
it's back =(

**Atom Version**: 0.181.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/burabure/.atom/packages/linter-flow/lib/linter-flow.coffee:27

TypeError: Cannot read property 'getPath' of undefined
  at LinterFlow.lintFile (/home/burabure/.atom/packages/linter-flow/lib/linter-flow.coffee:27:46)
  at /home/burabure/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /home/burabure/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-edark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
base16-edark-syntax, v0.0.0
emmet, v2.3.6
file-icons, v1.5.1
jsonlint, v1.0.2
language-liquid, v0.2.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-eslint, v0.5.0
linter-flow, v0.1.4
linter-htmlhint, v0.0.12
react, v0.11.2
script, v2.18.0
symbols-tree-view, v0.9.1
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by DylanLukes** [comment]
Also on OS X. Can't use the linter :(.

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/dylan/.atom/packages/linter-flow/lib/linter-flow.coffee:27

TypeError: Cannot read property 'getPath' of undefined
  at LinterFlow.lintFile (/Users/dylan/.atom/packages/linter-flow/lib/linter-flow.coffee:27:46)
  at /Users/dylan/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/dylan/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "gocode"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.1.2
autocomplete-plus, v2.10.0
emmet, v2.3.7
language-elixir, v0.4.0
linter, v0.12.0
linter-flow, v0.1.4

# Dev
No dev packages
```

**Comment by nmn** [comment]
It should be fine now.
