### ISSUE TITLE
Uncaught SyntaxError: Unexpected token C

### ISSUE THREAD

**Issue by l4u** [AtomLinter/linter-flow#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.4

### Stack Trace

Uncaught SyntaxError: Unexpected token C

```
At file:///opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2FLeo%2FProjects%2Fbalfear3%22%7D%5D%2C%22bootstrapScript%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2Flatest%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2Flatest%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.190.0%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2FLeo%2FProjects%2Fbalfear2%22%2C%22%2FUsers%2FLeo%2FProjects%2Fbalfear3%22%5D%7D:1

SyntaxError: Unexpected token C
  at Object.parse (native)
  at Socket.<anonymous> (/Users/Leo/.atom/packages/linter-flow/lib/linter-flow.coffee:35:19)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:32.0 application:add-project-folder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:18.2 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:16.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:16.8 core:cancel (atom-text-editor.editor.mini)
     -0:04.4 pane:show-previous-item (atom-text-editor.editor.vim-mode.command-mode)
     -0:03.8 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.4 pane:show-previous-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.1 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode)
     -0:02.0 pane:show-previous-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.6 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "minimap",
      "jshint",
      "highlight-line",
      "atom-lint",
      "linter",
      "linter-jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-typescript, v2.14.0
autoclose-html, v0.15.0
autocomplete-clang, v0.6.4
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
docblockr, v0.6.3
editorconfig, v0.3.3
file-icons, v1.5.4
git-log, v0.3.0
git-projects, v1.13.0
git-tab-status, v1.6.0
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
jsformat, v0.7.18
language-SCSS, v0.2.0
language-elixir, v0.4.0
language-erlang, v2.0.0
language-haml, v0.19.0
language-jade, v0.3.0
language-swift, v0.3.0
linter, v0.12.0
linter-clang, v2.25.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-elixirc, v0.2.1
linter-erlc, v0.2.0
linter-flow, v0.1.4
linter-haml, v0.1.1
linter-hlint, v0.3.1
linter-htmlhint, v0.0.12
linter-js-yaml, v1.0.0
linter-jscs, v1.10.0
linter-less, v0.3.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
linter-swiftc, v0.2.2
linter-tslint, v0.2.1
markdown-format, v2.5.0
meteor-api, v2.12.0
open-last-project, v0.3.5
permute, v0.1.0
pretty-json, v0.3.2
project-manager, v1.15.5
react, v0.11.2
script, v2.18.0
tabs-to-spaces, v0.9.2
text-manipulation, v0.4.0
vim-mode, v0.43.0
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by Ptival** [comment]
This keeps happening to me. I have fewer user packages, if this helps.



**Atom Version**: 0.190.0-d9f0f23
**System**: linux 3.19.3-3-ARCH
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.4

### Stack Trace

Uncaught SyntaxError: Unexpected token l

```
At file:///usr/local/share/atom/resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fvrobert%2FPeaCoq%22%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Flocal%2Fshare%2Fatom%2Fresources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Flocal%2Fshare%2Fatom%2Fresources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.190.0-d9f0f23%22%2C%22shellLoadTime%22%3A461%2C%22initialPaths%22%3A%5B%22%2Fhome%2Fvrobert%2FPeaCoq%22%5D%7D:1

SyntaxError: Unexpected token l
  at Object.parse (native)
  at Socket.<anonymous> (/home/vrobert/.atom/packages/linter-flow/lib/linter-flow.coffee:35:19)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -8:24.5 core:save (atom-text-editor.editor.is-focused)
  4x -8:23.8 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -8:22.5 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -8:22.1 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -7:51.8 core:move-left (atom-text-editor.editor)
     -7:50.8 core:backspace (atom-text-editor.editor)
     -7:50.4 core:delete (atom-text-editor.editor)
     -7:49.9 core:save (atom-text-editor.editor)
     -7:46.5 editor:consolidate-selections (atom-text-editor.editor)
     -7:46.5 core:cancel (atom-text-editor.editor)
     -0:09.0 core:move-down (atom-text-editor.editor)
     -0:08.7 core:move-up (atom-text-editor.editor)
     -0:07.9 core:save (atom-text-editor.editor)
     -0:06.5 editor:consolidate-selections (atom-text-editor.editor)
     -0:06.5 core:cancel (atom-text-editor.editor)
     -0:03.1 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-jshint",
      "atom-beautify",
      "jsformat"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
block-travel, v1.0.2
flow, v0.4.0
haxe, v0.6.1
language-haxe, v0.2.1
linter, v0.12.0
linter-flow, v0.1.4
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by rainboxx** [comment]
#16 and #17 are duplicates of each other, basically the package tries to parse non-JSON which seems to contain log output beside the JSON..

**Comment by nmn** [comment]
Closing as no longer applies. please create a new issue for any new problems you encounter.
