### ISSUE TITLE
Uncaught SyntaxError: Unexpected token F

### ISSUE THREAD

**Issue by derekr** [AtomLinter/linter-flow#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.4

### Stack Trace

Uncaught SyntaxError: Unexpected token F

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fdrk%2Fdev%2Fnerdwallet%2Flife-events%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.194.0%22%2C%22shellLoadTime%22%3A534%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fdrk%2Fdev%2Fnerdwallet%2Flife-events%22%5D%7D:1

SyntaxError: Unexpected token F
  at Object.parse (native)
  at Socket.<anonymous> (/Users/drk/.atom/packages/linter-flow/lib/linter-flow.coffee:35:19)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:09.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.2.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:04.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.1.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:04.1.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:02.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ],
    "disabledPackages": [
      "linter-js-standard"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.6.0
autocomplete-plus, v2.12.0
color-picker, v1.7.0
editorconfig, v1.0.0
file-icons, v1.5.4
file-types, v0.3.0
js-refactor, v0.3.0
linter, v0.12.1
linter-flow, v0.1.4
monokai-syntax-for-one-dark, v0.2.2
pigments, v0.1.2
refactor, v0.4.1
symbols-tree-view, v0.9.2

# Dev
No dev packages
```

**Comment by rainboxx** [comment]
This happened for me when saving a new buffer with JavaScript content to disc. Console logs showed this right before the exception:

``` Flow server launched for /Users/md/Documents/workspace/vt/vt
Spawned flow server (child pid=97722)
Logs will go to /var/folders/h1/jrpt7h754674105kk904_3kr0000gn/T/flow/zSUserszSmdzSDocumentszSworkspacezSvtzSvt.log
The flow server will be ready in a moment.
flow server still initializing. If it was just started this can take some time. Retrying... -
flow server still initializing. If it was just started this can take some time. Retrying... \
flow server still initializing. If it was just started this can take some time. Retrying... |
Error: flow server is busy
flow server still initializing. If it was just started this can take some time. Retrying... /
flow server still initializing. If it was just started this can take some time. Retrying... -
flow server still initializing. If it was just started this can take some time. Retrying... \
flow server still initializing. If it was just started this can take some time. Retrying... |
flow server still initializing. If it was just started this can take some time. Retrying... /
{"passed":false,"errors":[{"message":[{"descr":"string\nThis type is incompatible with","code":0,"path":"/Users/md/Documents/workspace/vt/vt/test.js","line":8,"endline":8,"start":5,"end":9},{"descr":"number","code":0,"path":"/Users/md/Documents/workspace/vt/vt/test.js","line":5,"endline":5,"start":12,"end":16}]}],"version":" Apr 25 2015 04:11:34"}
```

The log file mentioned in the console logs contained the following:

```
[2015-05-04 10:04:36] Initializing Server (This might take some time)
[2015-05-04 10:04:48] Server is READY
[2015-05-04 10:04:48] Took 11.889468 seconds to initialize.
recheck 1 files:
1/1: /Users/md/Documents/workspace/vt/vt/test.js
remerge 0 dependent files:
Status: Error
recheck 1 files:
1/1: /Users/md/Documents/workspace/vt/vt/test.js
remerge 0 dependent files:
recheck 1 files:
1/1: /Users/md/Documents/workspace/vt/vt/test.js
remerge 0 dependent files:
recheck 1 files:
1/1: /Users/md/Documents/workspace/vt/vt/test.js
remerge 0 dependent files:
```

**Comment by rainboxx** [comment]
Oh, and the content has been the first example from http://flowtype.org/docs/five-simple-examples.html#1-hello-flow:

```js
/* @flow */

function foo(x) {
  return x * 10;
}

foo('Hello, world!');
```

**Comment by nmn** [comment]
Should be fixed now.
