### ISSUE TITLE
Arguments.path.join must be strings

### ISSUE THREAD

**Issue by nijikokun** [AtomLinter/linter-flow#2]
```
Uncaught TypeError: Arguments to path.join must be strings path.js:384
exports.join path.js:384
LinterFlow linter-flow.coffee:87
LinterView.init
Linters linter-view.coffee:61
LinterView
```

**Comment by burabure** [comment]
getting this on Ubuntu 14.04. flow on PATH

```
 Failed to activate package named 'linter' TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:472:13)
    at new LinterFlow (/home/burabure/.atom/packages/linter-flow/lib/linter-flow.coffee:128:46)
    at LinterView.initLinters (/home/burabure/.atom/packages/linter/lib/linter-view.coffee:64:43)
    at new LinterView (/home/burabure/.atom/packages/linter/lib/linter-view.coffee:45:12)
    at /home/burabure/.atom/packages/linter/lib/init.coffee:106:24
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:272:9)
    at LinterInitializer.activate (/home/burabure/.atom/packages/linter/lib/init.coffee:100:52)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:235:27)
    at /usr/share/atom/resources/app/src/package.js:221:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
```

**Comment by paulcbetts** [comment]
Can you give this a try in the latest version?

**Comment by burabure** [comment]
Nope =(


**Atom Version**: 0.181.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/burabure/.atom/packages/linter-flow/lib/linter-flow.coffee:27

TypeError: Cannot read property 'getPath' of undefined
  at LinterFlow.lintFile (/home/burabure/.atom/packages/linter-flow/lib/linter-flow.coffee:27:46)
  at /home/burabure/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /home/burabure/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-edark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
base16-edark-syntax, v0.0.0
emmet, v2.3.4
file-icons, v1.5.1
jsonlint, v1.0.2
language-liquid, v0.2.0
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-eslint, v0.5.0
linter-flow, v0.1.4
linter-htmlhint, v0.0.8
react, v0.10.1
script, v2.18.0
symbols-tree-view, v0.8.1
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by paulcbetts** [comment]
...I may have published it to npm :man::gun:
