### ISSUE TITLE
When closing js tabs Linter Flow throws an error

### ISSUE THREAD

**Issue by mesosteros** [AtomLinter/linter-flow#7]
[Enter steps to reproduce below:]

1. Close an open javascript file tab

**Atom Version**: 0.176.0
**System**: Microsoft Windows 8.1
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1130

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1130:26)
  at exports.spawn (child_process.js:989:9)
  at LinterFlow.destroy (c:\Users\mesos_000\.atom\packages\linter-flow\lib\linter-flow.coffee:119:5)
  at LinterView.remove (c:\Users\mesos_000\.atom\packages\linter\lib\linter-view.coffee:212:7)
  at c:\Users\mesos_000\.atom\packages\linter\lib\linter-view.coffee:106:8
  at Emitter.module.exports.Emitter.emit (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:270:27)
  at TextEditor.module.exports.Model.destroy (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\node_modules\theorist\lib\model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:459:18)
  at HTMLDivElement.<anonymous> (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\node_modules\tabs\lib\tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (c:\Users\mesos_000\AppData\Local\atom\app-0.176.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -5:02.3 core:confirm (atom-text-editor.editor.mini)
  9x -4:46.8 core:page-down (atom-text-editor.editor)
  2x -2:14.7 core:confirm (atom-text-editor.editor.mini)
     -0:50.7 find-and-replace:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".meteor"
    ],
    "disabledPackages": [
      "autoflow",
      "background-tips",
      "dev-live-reload",
      "exception-reporting",
      "markdown-preview",
      "open-on-github",
      "package-generator",
      "styleguide",
      "timecop",
      "welcome",
      "update-package-dependencies",
      "symbols-view",
      "file-icons",
      "enhanced-package-list",
      "themed-settings",
      "metrics",
      "git-control",
      "deprecation-cop",
      "linter-flow"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
alignment, v1.1.3
atom-color-highlight, v3.0.5
atom-ctags, v2.5.5
autocomplete-paths, v1.0.0
autocomplete-plus, v2.0.2
autocomplete-plus-async, v0.22.0
block-cursor, v0.7.3
color-picker, v1.4.4
crosshairs, v0.1.2
git-tab-status, v1.5.3
linter, v0.10.1
linter-csslint, v0.0.11
linter-eslint, v0.3.1
linter-htmlhint, v0.0.8
linter-jscs, v1.4.9
meteor-api, v2.9.0
method-separator, v0.1.3
minimap, v3.5.6
seti-syntax, v0.2.1
seti-ui, v0.6.3
toolbar, v0.0.10
toolbar-main, v0.0.5
windows-context-menu, v0.3.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by paulcbetts** [comment]
Can you give this a try in the latest version?
