### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by atalargo** [AtomLinter/linter-flow#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1130

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1130:26)
  at exports.spawn (child_process.js:989:9)
  at LinterFlow.destroy (/Users/fruardum/.atom/packages/linter-flow/lib/linter-flow.coffee:119:5)
  at LinterView.remove (/Users/fruardum/.atom/packages/linter/lib/linter-view.coffee:212:7)
  at /Users/fruardum/.atom/packages/linter/lib/linter-view.coffee:106:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:270:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:459:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:716:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:760:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -3:21.7 core:select-all (atom-text-editor.editor)
     -3:19.5 copy-as-rtf:copy (atom-text-editor.editor)
     -3:15.4 command-palette:toggle (atom-text-editor.editor)
  4x -3:09.4 copy-as-rtf:copy (atom-text-editor.editor)
     -1:26.5 core:select-all (atom-text-editor.editor)
     -1:23.7 copy-as-rtf:copy (atom-text-editor.editor)
     -0:42.2 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -0:07.1 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "composer",
      "behat-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
autocomplete-plus, v2.0.2
coffee-lint, v0.7.3
copy-as-rtf, v0.5.0
git-log, v0.2.0
git-tab-status, v1.5.3
jsonlint, v1.0.0
language-twig, v1.5.2
linter, v0.10.1
linter-csslint, v0.0.11
linter-flow, v0.1.3
linter-haml, v0.1.0
linter-php, v0.0.11
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
linter-scss-lint, v0.0.11
php-twig, v3.0.0
phpunit, v1.0.9
phpunit-snippets, v0.1.0
project-manager, v1.15.4
rsense, v0.6.0
ruby-block-converter, v3.1.0
script, v2.16.0
slash-closer, v0.7.1
symbols-tree-view, v0.4.0
symfony-snippets, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by frederickfogerty** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1130

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1130:26)
  at exports.spawn (child_process.js:989:9)
  at LinterFlow.destroy (/Users/frederickf/.atom/packages/linter-flow/lib/linter-flow.coffee:119:5)
  at LinterView.remove (/Users/frederickf/.atom/packages/linter/lib/linter-view.coffee:212:7)
  at /Users/frederickf/.atom/packages/linter/lib/linter-view.coffee:106:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:270:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:459:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:716:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:760:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:45.8 core:save (atom-text-editor.editor)
     -0:36.6 editor:consolidate-selections (atom-text-editor.editor)
     -0:36.6 core:cancel (atom-text-editor.editor)
  8x -0:36.4 core:move-down (atom-text-editor.editor)
     -0:34.7 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:34.5 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:34.5 editor:newline (atom-text-editor.editor)
  5x -0:32.4 core:backspace (atom-text-editor.editor)
  2x -0:22.1 core:move-right (atom-text-editor.editor)
  4x -0:20.4 core:backspace (atom-text-editor.editor)
     -0:17.2 core:move-right (atom-text-editor.editor)
     -0:16.5 core:backspace (atom-text-editor.editor)
     -0:15.3 core:move-left (atom-text-editor.editor)
     -0:14.6 core:save (atom-text-editor.editor)
     -0:14.2 core:move-right (atom-text-editor.editor)
  3x -0:02.4 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "ide-flow"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.2
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
block-comment, v0.4.1
color-picker, v1.4.3
emmet, v2.3.2
language-js-specs, v0.1.0
linter, v0.10.1
linter-flow, v0.1.3
linter-jsxhint, v0.1.0
react, v0.8.8
recent-files, v0.3.0
require, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by paulcbetts** [comment]
Can you give this a try in the latest version?
