### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by Andersos** [AtomLinter/linter-flow#9]
[Enter steps to reproduce below:]

1. Open some files
2. Close all files by holding in cmd + W

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-flow](https://github.com/AtomLinter/linter-flow) package, v0.1.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1160

Error: spawn EACCES
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at exports.spawn (child_process.js:993:9)
  at LinterFlow.destroy (/Users/Andersos/.atom/packages/linter-flow/lib/linter-flow.coffee:119:5)
  at LinterView.remove (/Users/Andersos/.atom/packages/linter/lib/linter-view.coffee:281:7)
  at /Users/Andersos/.atom/packages/linter/lib/linter-view.coffee:111:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:270:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:459:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:716:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:760:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
 20x -0:01.3 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-sql"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
autocomplete-plus, v2.0.11
color-gutter, v0.3.1
editorconfig, v0.3.0
linter, v0.11.1
linter-csslint, v0.0.11
linter-flow, v0.1.3
linter-htmlhint, v0.0.8
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-jsxhint, v0.1.0
linter-less, v0.3.1
linter-scss-lint, v0.0.11
linter-shellcheck, v0.0.6
linter-tidy, v0.0.1
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by jayplattuk** [comment]
I've got the same issue. Any solution yet?

**Comment by paulcbetts** [comment]
@jayplattuk Can you give the latest version a try?
